services:
  front:
    # build: .
    image: http://10.134.200.50:5000/t-nsa-frontend:latest
    ports:
      - 8080:80
    environment:
      REACT_APP_API_URL: "localhost:3000"
#      PUBLIC_URL: "localhost:8080"
    restart: always