services:
  api:
    container_name: dev_api
    image: http://10.134.200.50:5000/t-nsa-backend:latest
    # build: .
    restart: always
    environment:
      DB_HOST: #IP_VM_DB
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: dev_db
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: bridge